//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsServiceAppTest.CrmWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/Kraan.WebservicesTemplate")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppVersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceOSVersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GebruikersNaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPhraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WachtwoordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode {
            get {
                return this.AppCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AppCodeField, value) != true)) {
                    this.AppCodeField = value;
                    this.RaisePropertyChanged("AppCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppVersie {
            get {
                return this.AppVersieField;
            }
            set {
                if ((object.ReferenceEquals(this.AppVersieField, value) != true)) {
                    this.AppVersieField = value;
                    this.RaisePropertyChanged("AppVersie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceOS {
            get {
                return this.DeviceOSField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceOSField, value) != true)) {
                    this.DeviceOSField = value;
                    this.RaisePropertyChanged("DeviceOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceOSVersie {
            get {
                return this.DeviceOSVersieField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceOSVersieField, value) != true)) {
                    this.DeviceOSVersieField = value;
                    this.RaisePropertyChanged("DeviceOSVersie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GebruikersNaam {
            get {
                return this.GebruikersNaamField;
            }
            set {
                if ((object.ReferenceEquals(this.GebruikersNaamField, value) != true)) {
                    this.GebruikersNaamField = value;
                    this.RaisePropertyChanged("GebruikersNaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPhrase {
            get {
                return this.UserPhraseField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPhraseField, value) != true)) {
                    this.UserPhraseField = value;
                    this.RaisePropertyChanged("UserPhrase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wachtwoord {
            get {
                return this.WachtwoordField;
            }
            set {
                if ((object.ReferenceEquals(this.WachtwoordField, value) != true)) {
                    this.WachtwoordField = value;
                    this.RaisePropertyChanged("Wachtwoord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRegistratie", Namespace="http://schemas.datacontract.org/2004/07/Kraan.WebservicesTemplate")]
    [System.SerializableAttribute()]
    public partial class LoginRegistratie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MeldingenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WebserverVersienummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Meldingen {
            get {
                return this.MeldingenField;
            }
            set {
                if ((object.ReferenceEquals(this.MeldingenField, value) != true)) {
                    this.MeldingenField = value;
                    this.RaisePropertyChanged("Meldingen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes {
            get {
                return this.SuccesField;
            }
            set {
                if ((this.SuccesField.Equals(value) != true)) {
                    this.SuccesField = value;
                    this.RaisePropertyChanged("Succes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WebserverVersienummer {
            get {
                return this.WebserverVersienummerField;
            }
            set {
                if ((this.WebserverVersienummerField.Equals(value) != true)) {
                    this.WebserverVersienummerField = value;
                    this.RaisePropertyChanged("WebserverVersienummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestAuth", Namespace="http://schemas.datacontract.org/2004/07/Kraan.WebservicesTemplate")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsServiceAppTest.CrmWebservice.RequestSearch))]
    public partial class RequestAuth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppVersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceOSVersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GebruikersNaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode {
            get {
                return this.AppCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AppCodeField, value) != true)) {
                    this.AppCodeField = value;
                    this.RaisePropertyChanged("AppCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppVersie {
            get {
                return this.AppVersieField;
            }
            set {
                if ((object.ReferenceEquals(this.AppVersieField, value) != true)) {
                    this.AppVersieField = value;
                    this.RaisePropertyChanged("AppVersie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceOS {
            get {
                return this.DeviceOSField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceOSField, value) != true)) {
                    this.DeviceOSField = value;
                    this.RaisePropertyChanged("DeviceOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceOSVersie {
            get {
                return this.DeviceOSVersieField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceOSVersieField, value) != true)) {
                    this.DeviceOSVersieField = value;
                    this.RaisePropertyChanged("DeviceOSVersie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GebruikersNaam {
            get {
                return this.GebruikersNaamField;
            }
            set {
                if ((object.ReferenceEquals(this.GebruikersNaamField, value) != true)) {
                    this.GebruikersNaamField = value;
                    this.RaisePropertyChanged("GebruikersNaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestSearch", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class RequestSearch : WindowsServiceAppTest.CrmWebservice.RequestAuth {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZoekStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZoekString {
            get {
                return this.ZoekStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoekStringField, value) != true)) {
                    this.ZoekStringField = value;
                    this.RaisePropertyChanged("ZoekString");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionMelding", Namespace="http://schemas.datacontract.org/2004/07/Kraan.WebservicesTemplate")]
    [System.SerializableAttribute()]
    public partial class ExceptionMelding : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnerExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StacktraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerExceptionMessage {
            get {
                return this.InnerExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionMessageField, value) != true)) {
                    this.InnerExceptionMessageField = value;
                    this.RaisePropertyChanged("InnerExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stacktrace {
            get {
                return this.StacktraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StacktraceField, value) != true)) {
                    this.StacktraceField = value;
                    this.RaisePropertyChanged("Stacktrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatieLijstModel", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class RelatieLijstModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LoginSuccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.CrmWebservice.Relatie[] RelatiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LoginSucces {
            get {
                return this.LoginSuccesField;
            }
            set {
                if ((this.LoginSuccesField.Equals(value) != true)) {
                    this.LoginSuccesField = value;
                    this.RaisePropertyChanged("LoginSucces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.CrmWebservice.Relatie[] Relaties {
            get {
                return this.RelatiesField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatiesField, value) != true)) {
                    this.RelatiesField = value;
                    this.RaisePropertyChanged("Relaties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relatie", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class Relatie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.CrmWebservice.ContactPersoon[] ContactpersonenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.CrmWebservice.Document[] DocumentenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailpriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailzakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GeboorteDatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeslachtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HuisnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBedrijfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KvkNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoepnaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StraatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoonnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoonnummeralgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoonnummerfaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoonnummermobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoonnummerzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToevoegingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WoonplaatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.CrmWebservice.ContactPersoon[] Contactpersonen {
            get {
                return this.ContactpersonenField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactpersonenField, value) != true)) {
                    this.ContactpersonenField = value;
                    this.RaisePropertyChanged("Contactpersonen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.CrmWebservice.Document[] Documenten {
            get {
                return this.DocumentenField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentenField, value) != true)) {
                    this.DocumentenField = value;
                    this.RaisePropertyChanged("Documenten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emailpri {
            get {
                return this.EmailpriField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailpriField, value) != true)) {
                    this.EmailpriField = value;
                    this.RaisePropertyChanged("Emailpri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emailzak {
            get {
                return this.EmailzakField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailzakField, value) != true)) {
                    this.EmailzakField = value;
                    this.RaisePropertyChanged("Emailzak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GeboorteDatum {
            get {
                return this.GeboorteDatumField;
            }
            set {
                if ((this.GeboorteDatumField.Equals(value) != true)) {
                    this.GeboorteDatumField = value;
                    this.RaisePropertyChanged("GeboorteDatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Geslacht {
            get {
                return this.GeslachtField;
            }
            set {
                if ((object.ReferenceEquals(this.GeslachtField, value) != true)) {
                    this.GeslachtField = value;
                    this.RaisePropertyChanged("Geslacht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Huisnummer {
            get {
                return this.HuisnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.HuisnummerField, value) != true)) {
                    this.HuisnummerField = value;
                    this.RaisePropertyChanged("Huisnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBedrijf {
            get {
                return this.IsBedrijfField;
            }
            set {
                if ((this.IsBedrijfField.Equals(value) != true)) {
                    this.IsBedrijfField = value;
                    this.RaisePropertyChanged("IsBedrijf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProject {
            get {
                return this.IsProjectField;
            }
            set {
                if ((this.IsProjectField.Equals(value) != true)) {
                    this.IsProjectField = value;
                    this.RaisePropertyChanged("IsProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KvkNummer {
            get {
                return this.KvkNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.KvkNummerField, value) != true)) {
                    this.KvkNummerField = value;
                    this.RaisePropertyChanged("KvkNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obnummer {
            get {
                return this.ObnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.ObnummerField, value) != true)) {
                    this.ObnummerField = value;
                    this.RaisePropertyChanged("Obnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectStatus {
            get {
                return this.ProjectStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectStatusField, value) != true)) {
                    this.ProjectStatusField = value;
                    this.RaisePropertyChanged("ProjectStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Roepnaam {
            get {
                return this.RoepnaamField;
            }
            set {
                if ((object.ReferenceEquals(this.RoepnaamField, value) != true)) {
                    this.RoepnaamField = value;
                    this.RaisePropertyChanged("Roepnaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Straat {
            get {
                return this.StraatField;
            }
            set {
                if ((object.ReferenceEquals(this.StraatField, value) != true)) {
                    this.StraatField = value;
                    this.RaisePropertyChanged("Straat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefoonnummer {
            get {
                return this.TelefoonnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoonnummerField, value) != true)) {
                    this.TelefoonnummerField = value;
                    this.RaisePropertyChanged("Telefoonnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefoonnummeralg {
            get {
                return this.TelefoonnummeralgField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoonnummeralgField, value) != true)) {
                    this.TelefoonnummeralgField = value;
                    this.RaisePropertyChanged("Telefoonnummeralg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefoonnummerfax {
            get {
                return this.TelefoonnummerfaxField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoonnummerfaxField, value) != true)) {
                    this.TelefoonnummerfaxField = value;
                    this.RaisePropertyChanged("Telefoonnummerfax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefoonnummermob {
            get {
                return this.TelefoonnummermobField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoonnummermobField, value) != true)) {
                    this.TelefoonnummermobField = value;
                    this.RaisePropertyChanged("Telefoonnummermob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefoonnummerza {
            get {
                return this.TelefoonnummerzaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoonnummerzaField, value) != true)) {
                    this.TelefoonnummerzaField = value;
                    this.RaisePropertyChanged("Telefoonnummerza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Toevoeging {
            get {
                return this.ToevoegingField;
            }
            set {
                if ((object.ReferenceEquals(this.ToevoegingField, value) != true)) {
                    this.ToevoegingField = value;
                    this.RaisePropertyChanged("Toevoeging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Woonplaats {
            get {
                return this.WoonplaatsField;
            }
            set {
                if ((object.ReferenceEquals(this.WoonplaatsField, value) != true)) {
                    this.WoonplaatsField = value;
                    this.RaisePropertyChanged("Woonplaats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPersoon", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class ContactPersoon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoepnaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Roepnaam {
            get {
                return this.RoepnaamField;
            }
            set {
                if ((object.ReferenceEquals(this.RoepnaamField, value) != true)) {
                    this.RoepnaamField = value;
                    this.RaisePropertyChanged("Roepnaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AanmaakDatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AppCreationGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BestandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocutypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AanmaakDatum {
            get {
                return this.AanmaakDatumField;
            }
            set {
                if ((this.AanmaakDatumField.Equals(value) != true)) {
                    this.AanmaakDatumField = value;
                    this.RaisePropertyChanged("AanmaakDatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AppCreationGuid {
            get {
                return this.AppCreationGuidField;
            }
            set {
                if ((this.AppCreationGuidField.Equals(value) != true)) {
                    this.AppCreationGuidField = value;
                    this.RaisePropertyChanged("AppCreationGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bestand {
            get {
                return this.BestandField;
            }
            set {
                if ((object.ReferenceEquals(this.BestandField, value) != true)) {
                    this.BestandField = value;
                    this.RaisePropertyChanged("Bestand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Docutype {
            get {
                return this.DocutypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocutypeField, value) != true)) {
                    this.DocutypeField = value;
                    this.RaisePropertyChanged("Docutype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extensie {
            get {
                return this.ExtensieField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensieField, value) != true)) {
                    this.ExtensieField = value;
                    this.RaisePropertyChanged("Extensie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pad {
            get {
                return this.PadField;
            }
            set {
                if ((object.ReferenceEquals(this.PadField, value) != true)) {
                    this.PadField = value;
                    this.RaisePropertyChanged("Pad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatieSingleModel", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class RelatieSingleModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LoginSuccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.CrmWebservice.Relatie RelatieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LoginSucces {
            get {
                return this.LoginSuccesField;
            }
            set {
                if ((this.LoginSuccesField.Equals(value) != true)) {
                    this.LoginSuccesField = value;
                    this.RaisePropertyChanged("LoginSucces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.CrmWebservice.Relatie Relatie {
            get {
                return this.RelatieField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatieField, value) != true)) {
                    this.RelatieField = value;
                    this.RaisePropertyChanged("Relatie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadRequest", Namespace="http://schemas.datacontract.org/2004/07/Kraan.WebservicesTemplate")]
    [System.SerializableAttribute()]
    public partial class DownloadRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedrijfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ObjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpdrachtcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.CrmWebservice.RequestAuth RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WerkboncodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bedrijf {
            get {
                return this.BedrijfField;
            }
            set {
                if ((object.ReferenceEquals(this.BedrijfField, value) != true)) {
                    this.BedrijfField = value;
                    this.RaisePropertyChanged("Bedrijf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FileId {
            get {
                return this.FileIdField;
            }
            set {
                if ((this.FileIdField.Equals(value) != true)) {
                    this.FileIdField = value;
                    this.RaisePropertyChanged("FileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileLocation {
            get {
                return this.FileLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.FileLocationField, value) != true)) {
                    this.FileLocationField = value;
                    this.RaisePropertyChanged("FileLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ObjectId {
            get {
                return this.ObjectIdField;
            }
            set {
                if ((this.ObjectIdField.Equals(value) != true)) {
                    this.ObjectIdField = value;
                    this.RaisePropertyChanged("ObjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opdrachtcode {
            get {
                return this.OpdrachtcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OpdrachtcodeField, value) != true)) {
                    this.OpdrachtcodeField = value;
                    this.RaisePropertyChanged("Opdrachtcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectCode {
            get {
                return this.ProjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectCodeField, value) != true)) {
                    this.ProjectCodeField = value;
                    this.RaisePropertyChanged("ProjectCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.CrmWebservice.RequestAuth Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Werkboncode {
            get {
                return this.WerkboncodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WerkboncodeField, value) != true)) {
                    this.WerkboncodeField = value;
                    this.RaisePropertyChanged("Werkboncode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrmWebservice.ICrmService")]
    public interface ICrmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/GetVersion", ReplyAction="http://tempuri.org/IAuthWebservice/GetVersionResponse")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/GetVersion", ReplyAction="http://tempuri.org/IAuthWebservice/GetVersionResponse")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/RegisterUser", ReplyAction="http://tempuri.org/IAuthWebservice/RegisterUserResponse")]
        WindowsServiceAppTest.CrmWebservice.LoginRegistratie RegisterUser(WindowsServiceAppTest.CrmWebservice.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/RegisterUser", ReplyAction="http://tempuri.org/IAuthWebservice/RegisterUserResponse")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.LoginRegistratie> RegisterUserAsync(WindowsServiceAppTest.CrmWebservice.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/UnRegisterUser", ReplyAction="http://tempuri.org/IAuthWebservice/UnRegisterUserResponse")]
        WindowsServiceAppTest.CrmWebservice.LoginRegistratie UnRegisterUser(WindowsServiceAppTest.CrmWebservice.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/UnRegisterUser", ReplyAction="http://tempuri.org/IAuthWebservice/UnRegisterUserResponse")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.LoginRegistratie> UnRegisterUserAsync(WindowsServiceAppTest.CrmWebservice.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/CheckLogin", ReplyAction="http://tempuri.org/IAuthWebservice/CheckLoginResponse")]
        WindowsServiceAppTest.CrmWebservice.LoginRegistratie CheckLogin(WindowsServiceAppTest.CrmWebservice.RequestAuth request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/CheckLogin", ReplyAction="http://tempuri.org/IAuthWebservice/CheckLoginResponse")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.LoginRegistratie> CheckLoginAsync(WindowsServiceAppTest.CrmWebservice.RequestAuth request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/DownloadLogFiles", ReplyAction="http://tempuri.org/IAuthWebservice/DownloadLogFilesResponse")]
        byte[] DownloadLogFiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/DownloadLogFiles", ReplyAction="http://tempuri.org/IAuthWebservice/DownloadLogFilesResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadLogFilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/SaveException", ReplyAction="http://tempuri.org/IAuthWebservice/SaveExceptionResponse")]
        void SaveException(WindowsServiceAppTest.CrmWebservice.ExceptionMelding exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWebservice/SaveException", ReplyAction="http://tempuri.org/IAuthWebservice/SaveExceptionResponse")]
        System.Threading.Tasks.Task SaveExceptionAsync(WindowsServiceAppTest.CrmWebservice.ExceptionMelding exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetFilterdListRelatie", ReplyAction="http://tempuri.org/ICrmService/GetFilterdListRelatieResponse")]
        WindowsServiceAppTest.CrmWebservice.RelatieLijstModel GetFilterdListRelatie(WindowsServiceAppTest.CrmWebservice.RequestSearch request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetFilterdListRelatie", ReplyAction="http://tempuri.org/ICrmService/GetFilterdListRelatieResponse")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.RelatieLijstModel> GetFilterdListRelatieAsync(WindowsServiceAppTest.CrmWebservice.RequestSearch request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetFilterdListProject", ReplyAction="http://tempuri.org/ICrmService/GetFilterdListProjectResponse")]
        WindowsServiceAppTest.CrmWebservice.RelatieLijstModel GetFilterdListProject(WindowsServiceAppTest.CrmWebservice.RequestSearch request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetFilterdListProject", ReplyAction="http://tempuri.org/ICrmService/GetFilterdListProjectResponse")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.RelatieLijstModel> GetFilterdListProjectAsync(WindowsServiceAppTest.CrmWebservice.RequestSearch request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetRelatie", ReplyAction="http://tempuri.org/ICrmService/GetRelatieResponse")]
        WindowsServiceAppTest.CrmWebservice.RelatieSingleModel GetRelatie(WindowsServiceAppTest.CrmWebservice.RequestSearch request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetRelatie", ReplyAction="http://tempuri.org/ICrmService/GetRelatieResponse")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.RelatieSingleModel> GetRelatieAsync(WindowsServiceAppTest.CrmWebservice.RequestSearch request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetFileStream", ReplyAction="http://tempuri.org/ICrmService/GetFileStreamResponse")]
        System.IO.Stream GetFileStream(WindowsServiceAppTest.CrmWebservice.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetFileStream", ReplyAction="http://tempuri.org/ICrmService/GetFileStreamResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetFileStreamAsync(WindowsServiceAppTest.CrmWebservice.DownloadRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrmServiceChannel : WindowsServiceAppTest.CrmWebservice.ICrmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrmServiceClient : System.ServiceModel.ClientBase<WindowsServiceAppTest.CrmWebservice.ICrmService>, WindowsServiceAppTest.CrmWebservice.ICrmService {
        
        public CrmServiceClient() {
        }
        
        public CrmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync() {
            return base.Channel.GetVersionAsync();
        }
        
        public WindowsServiceAppTest.CrmWebservice.LoginRegistratie RegisterUser(WindowsServiceAppTest.CrmWebservice.Login login) {
            return base.Channel.RegisterUser(login);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.LoginRegistratie> RegisterUserAsync(WindowsServiceAppTest.CrmWebservice.Login login) {
            return base.Channel.RegisterUserAsync(login);
        }
        
        public WindowsServiceAppTest.CrmWebservice.LoginRegistratie UnRegisterUser(WindowsServiceAppTest.CrmWebservice.Login login) {
            return base.Channel.UnRegisterUser(login);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.LoginRegistratie> UnRegisterUserAsync(WindowsServiceAppTest.CrmWebservice.Login login) {
            return base.Channel.UnRegisterUserAsync(login);
        }
        
        public WindowsServiceAppTest.CrmWebservice.LoginRegistratie CheckLogin(WindowsServiceAppTest.CrmWebservice.RequestAuth request) {
            return base.Channel.CheckLogin(request);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.LoginRegistratie> CheckLoginAsync(WindowsServiceAppTest.CrmWebservice.RequestAuth request) {
            return base.Channel.CheckLoginAsync(request);
        }
        
        public byte[] DownloadLogFiles() {
            return base.Channel.DownloadLogFiles();
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadLogFilesAsync() {
            return base.Channel.DownloadLogFilesAsync();
        }
        
        public void SaveException(WindowsServiceAppTest.CrmWebservice.ExceptionMelding exception) {
            base.Channel.SaveException(exception);
        }
        
        public System.Threading.Tasks.Task SaveExceptionAsync(WindowsServiceAppTest.CrmWebservice.ExceptionMelding exception) {
            return base.Channel.SaveExceptionAsync(exception);
        }
        
        public WindowsServiceAppTest.CrmWebservice.RelatieLijstModel GetFilterdListRelatie(WindowsServiceAppTest.CrmWebservice.RequestSearch request) {
            return base.Channel.GetFilterdListRelatie(request);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.RelatieLijstModel> GetFilterdListRelatieAsync(WindowsServiceAppTest.CrmWebservice.RequestSearch request) {
            return base.Channel.GetFilterdListRelatieAsync(request);
        }
        
        public WindowsServiceAppTest.CrmWebservice.RelatieLijstModel GetFilterdListProject(WindowsServiceAppTest.CrmWebservice.RequestSearch request) {
            return base.Channel.GetFilterdListProject(request);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.RelatieLijstModel> GetFilterdListProjectAsync(WindowsServiceAppTest.CrmWebservice.RequestSearch request) {
            return base.Channel.GetFilterdListProjectAsync(request);
        }
        
        public WindowsServiceAppTest.CrmWebservice.RelatieSingleModel GetRelatie(WindowsServiceAppTest.CrmWebservice.RequestSearch request) {
            return base.Channel.GetRelatie(request);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.CrmWebservice.RelatieSingleModel> GetRelatieAsync(WindowsServiceAppTest.CrmWebservice.RequestSearch request) {
            return base.Channel.GetRelatieAsync(request);
        }
        
        public System.IO.Stream GetFileStream(WindowsServiceAppTest.CrmWebservice.DownloadRequest request) {
            return base.Channel.GetFileStream(request);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetFileStreamAsync(WindowsServiceAppTest.CrmWebservice.DownloadRequest request) {
            return base.Channel.GetFileStreamAsync(request);
        }
    }
}
