//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsServiceAppTest.Sales24 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", ConfigurationName="Sales24.MessageServiceSoap")]
    public interface MessageServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (GetAvailableMessagesRequest) of message GetAvailableMessagesRequest does not match the default value (GetAvailableMessages)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oosterberg.nl/messageservice/GetAvailableMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsServiceAppTest.Sales24.GetAvailableMessagesResponse GetAvailableMessages(WindowsServiceAppTest.Sales24.GetAvailableMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oosterberg.nl/messageservice/GetAvailableMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.GetAvailableMessagesResponse> GetAvailableMessagesAsync(WindowsServiceAppTest.Sales24.GetAvailableMessagesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetMessageRequest) of message GetMessageRequest does not match the default value (GetMessage)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oosterberg.nl/messageservice/GetMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsServiceAppTest.Sales24.GetMessageResponse GetMessage(WindowsServiceAppTest.Sales24.GetMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oosterberg.nl/messageservice/GetMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.GetMessageResponse> GetMessageAsync(WindowsServiceAppTest.Sales24.GetMessageRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DeleteMessageRequest) of message DeleteMessageRequest does not match the default value (DeleteMessage)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oosterberg.nl/messageservice/DeleteMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsServiceAppTest.Sales24.DeleteMessageResponse DeleteMessage(WindowsServiceAppTest.Sales24.DeleteMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oosterberg.nl/messageservice/DeleteMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.DeleteMessageResponse> DeleteMessageAsync(WindowsServiceAppTest.Sales24.DeleteMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oosterberg.nl/messageservice/PostMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsServiceAppTest.Sales24.PostMessageResponse PostMessage(WindowsServiceAppTest.Sales24.PostMessageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.oosterberg.nl/messageservice/PostMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.PostMessageResponse> PostMessageAsync(WindowsServiceAppTest.Sales24.PostMessageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class AuthenticationInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationIdField;
        
        private string versionIdField;
        
        private string relationIdField;
        
        private string userIdField;
        
        private string passwordField;
        
        private string sessionIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
                this.RaisePropertyChanged("ApplicationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string VersionId {
            get {
                return this.versionIdField;
            }
            set {
                this.versionIdField = value;
                this.RaisePropertyChanged("VersionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string RelationId {
            get {
                return this.relationIdField;
            }
            set {
                this.relationIdField = value;
                this.RaisePropertyChanged("RelationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("SessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class Attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uRLField;
        
        private string documentTypeField;
        
        private string fileTypeField;
        
        private string fileNameField;
        
        private byte[] attachedDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=4)]
        public byte[] AttachedData {
            get {
                return this.attachedDataField;
            }
            set {
                this.attachedDataField = value;
                this.RaisePropertyChanged("AttachedData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class MessageServiceMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgIdField;
        
        private string msgTypeField;
        
        private string msgFormatField;
        
        private string msgVersionField;
        
        private System.Nullable<System.DateTime> msgDateTimeField;
        
        private Attachment[] attachmentField;
        
        private System.Xml.XmlNode[] msgContentField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("MsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MsgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("MsgType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string MsgFormat {
            get {
                return this.msgFormatField;
            }
            set {
                this.msgFormatField = value;
                this.RaisePropertyChanged("MsgFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MsgVersion {
            get {
                return this.msgVersionField;
            }
            set {
                this.msgVersionField = value;
                this.RaisePropertyChanged("MsgVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> MsgDateTime {
            get {
                return this.msgDateTimeField;
            }
            set {
                this.msgDateTimeField = value;
                this.RaisePropertyChanged("MsgDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Order=5)]
        public Attachment[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
                this.RaisePropertyChanged("Attachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MsgContent", Order=6)]
        public System.Xml.XmlNode[] MsgContent {
            get {
                return this.msgContentField;
            }
            set {
                this.msgContentField = value;
                this.RaisePropertyChanged("MsgContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class CustomInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isTestMessageField;
        
        private string languageCodeField;
        
        private System.Nullable<bool> isContentCompressedField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsTestMessage {
            get {
                return this.isTestMessageField;
            }
            set {
                this.isTestMessageField = value;
                this.RaisePropertyChanged("IsTestMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("LanguageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<bool> IsContentCompressed {
            get {
                return this.isContentCompressedField;
            }
            set {
                this.isContentCompressedField = value;
                this.RaisePropertyChanged("IsContentCompressed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class AvailableFormat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgFormatField;
        
        private string msgVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MsgFormat {
            get {
                return this.msgFormatField;
            }
            set {
                this.msgFormatField = value;
                this.RaisePropertyChanged("MsgFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MsgVersion {
            get {
                return this.msgVersionField;
            }
            set {
                this.msgVersionField = value;
                this.RaisePropertyChanged("MsgVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
    public partial class MessageServiceAvailableMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgIdField;
        
        private System.DateTime msgDateTimeField;
        
        private AvailableFormat[] availableFormatField;
        
        private string msgTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("MsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime MsgDateTime {
            get {
                return this.msgDateTimeField;
            }
            set {
                this.msgDateTimeField = value;
                this.RaisePropertyChanged("MsgDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvailableFormat", Order=2)]
        public AvailableFormat[] AvailableFormat {
            get {
                return this.availableFormatField;
            }
            set {
                this.availableFormatField = value;
                this.RaisePropertyChanged("AvailableFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string MsgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("MsgType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvailableMessagesRequest", WrapperNamespace="http://etim.nl/xmlschemas/messageservice/2.40", IsWrapped=true)]
    public partial class GetAvailableMessagesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
        public WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
        public WindowsServiceAppTest.Sales24.CustomInfo CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgType;
        
        public GetAvailableMessagesRequest() {
        }
        
        public GetAvailableMessagesRequest(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, string MsgType) {
            this.AuthenticationInfo = AuthenticationInfo;
            this.CustomInfo = CustomInfo;
            this.MsgType = MsgType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAvailableMessagesResponse", WrapperNamespace="http://etim.nl/xmlschemas/messageservice/2.40", IsWrapped=true)]
    public partial class GetAvailableMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MessageServiceAvailableMessage")]
        public WindowsServiceAppTest.Sales24.MessageServiceAvailableMessage[] MessageServiceAvailableMessage;
        
        public GetAvailableMessagesResponse() {
        }
        
        public GetAvailableMessagesResponse(WindowsServiceAppTest.Sales24.MessageServiceAvailableMessage[] MessageServiceAvailableMessage) {
            this.MessageServiceAvailableMessage = MessageServiceAvailableMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageRequest", WrapperNamespace="http://etim.nl/xmlschemas/messageservice/2.40", IsWrapped=true)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
        public WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
        public WindowsServiceAppTest.Sales24.CustomInfo CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgFormat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgVersion;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, string MsgId, string MsgFormat, string MsgVersion) {
            this.AuthenticationInfo = AuthenticationInfo;
            this.CustomInfo = CustomInfo;
            this.MsgId = MsgId;
            this.MsgFormat = MsgFormat;
            this.MsgVersion = MsgVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageResponse", WrapperNamespace="http://etim.nl/xmlschemas/messageservice/2.40", IsWrapped=true)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WindowsServiceAppTest.Sales24.MessageServiceMessage MessageServiceMessage;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(WindowsServiceAppTest.Sales24.MessageServiceMessage MessageServiceMessage) {
            this.MessageServiceMessage = MessageServiceMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteMessageRequest", WrapperNamespace="http://etim.nl/xmlschemas/messageservice/2.40", IsWrapped=true)]
    public partial class DeleteMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
        public WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
        public WindowsServiceAppTest.Sales24.CustomInfo CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgId;
        
        public DeleteMessageRequest() {
        }
        
        public DeleteMessageRequest(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, string MsgId) {
            this.AuthenticationInfo = AuthenticationInfo;
            this.CustomInfo = CustomInfo;
            this.MsgId = MsgId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteMessageResponse", WrapperNamespace="http://etim.nl/xmlschemas/messageservice/2.40", IsWrapped=true)]
    public partial class DeleteMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        public bool DeleteMessageResult;
        
        public DeleteMessageResponse() {
        }
        
        public DeleteMessageResponse(bool DeleteMessageResult) {
            this.DeleteMessageResult = DeleteMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostMessageRequest", WrapperNamespace="http://etim.nl/xmlschemas/messageservice/2.40", IsWrapped=true)]
    public partial class PostMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
        public WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40")]
        public WindowsServiceAppTest.Sales24.CustomInfo CustomInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WindowsServiceAppTest.Sales24.MessageServiceMessage MessageServiceMessage;
        
        public PostMessageRequest() {
        }
        
        public PostMessageRequest(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, WindowsServiceAppTest.Sales24.MessageServiceMessage MessageServiceMessage) {
            this.AuthenticationInfo = AuthenticationInfo;
            this.CustomInfo = CustomInfo;
            this.MessageServiceMessage = MessageServiceMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostMessageResponse", WrapperNamespace="http://etim.nl/xmlschemas/messageservice/2.40", IsWrapped=true)]
    public partial class PostMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WindowsServiceAppTest.Sales24.MessageServiceMessage MessageServiceMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://etim.nl/xmlschemas/messageservice/2.40", Order=1)]
        public bool PostMessageResult;
        
        public PostMessageResponse() {
        }
        
        public PostMessageResponse(WindowsServiceAppTest.Sales24.MessageServiceMessage MessageServiceMessage, bool PostMessageResult) {
            this.MessageServiceMessage = MessageServiceMessage;
            this.PostMessageResult = PostMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageServiceSoapChannel : WindowsServiceAppTest.Sales24.MessageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceSoapClient : System.ServiceModel.ClientBase<WindowsServiceAppTest.Sales24.MessageServiceSoap>, WindowsServiceAppTest.Sales24.MessageServiceSoap {
        
        public MessageServiceSoapClient() {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsServiceAppTest.Sales24.GetAvailableMessagesResponse WindowsServiceAppTest.Sales24.MessageServiceSoap.GetAvailableMessages(WindowsServiceAppTest.Sales24.GetAvailableMessagesRequest request) {
            return base.Channel.GetAvailableMessages(request);
        }
        
        public WindowsServiceAppTest.Sales24.MessageServiceAvailableMessage[] GetAvailableMessages(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, string MsgType) {
            WindowsServiceAppTest.Sales24.GetAvailableMessagesRequest inValue = new WindowsServiceAppTest.Sales24.GetAvailableMessagesRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.CustomInfo = CustomInfo;
            inValue.MsgType = MsgType;
            WindowsServiceAppTest.Sales24.GetAvailableMessagesResponse retVal = ((WindowsServiceAppTest.Sales24.MessageServiceSoap)(this)).GetAvailableMessages(inValue);
            return retVal.MessageServiceAvailableMessage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.GetAvailableMessagesResponse> WindowsServiceAppTest.Sales24.MessageServiceSoap.GetAvailableMessagesAsync(WindowsServiceAppTest.Sales24.GetAvailableMessagesRequest request) {
            return base.Channel.GetAvailableMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.GetAvailableMessagesResponse> GetAvailableMessagesAsync(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, string MsgType) {
            WindowsServiceAppTest.Sales24.GetAvailableMessagesRequest inValue = new WindowsServiceAppTest.Sales24.GetAvailableMessagesRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.CustomInfo = CustomInfo;
            inValue.MsgType = MsgType;
            return ((WindowsServiceAppTest.Sales24.MessageServiceSoap)(this)).GetAvailableMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsServiceAppTest.Sales24.GetMessageResponse WindowsServiceAppTest.Sales24.MessageServiceSoap.GetMessage(WindowsServiceAppTest.Sales24.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public WindowsServiceAppTest.Sales24.MessageServiceMessage GetMessage(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, string MsgId, string MsgFormat, string MsgVersion) {
            WindowsServiceAppTest.Sales24.GetMessageRequest inValue = new WindowsServiceAppTest.Sales24.GetMessageRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.CustomInfo = CustomInfo;
            inValue.MsgId = MsgId;
            inValue.MsgFormat = MsgFormat;
            inValue.MsgVersion = MsgVersion;
            WindowsServiceAppTest.Sales24.GetMessageResponse retVal = ((WindowsServiceAppTest.Sales24.MessageServiceSoap)(this)).GetMessage(inValue);
            return retVal.MessageServiceMessage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.GetMessageResponse> WindowsServiceAppTest.Sales24.MessageServiceSoap.GetMessageAsync(WindowsServiceAppTest.Sales24.GetMessageRequest request) {
            return base.Channel.GetMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.GetMessageResponse> GetMessageAsync(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, string MsgId, string MsgFormat, string MsgVersion) {
            WindowsServiceAppTest.Sales24.GetMessageRequest inValue = new WindowsServiceAppTest.Sales24.GetMessageRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.CustomInfo = CustomInfo;
            inValue.MsgId = MsgId;
            inValue.MsgFormat = MsgFormat;
            inValue.MsgVersion = MsgVersion;
            return ((WindowsServiceAppTest.Sales24.MessageServiceSoap)(this)).GetMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsServiceAppTest.Sales24.DeleteMessageResponse WindowsServiceAppTest.Sales24.MessageServiceSoap.DeleteMessage(WindowsServiceAppTest.Sales24.DeleteMessageRequest request) {
            return base.Channel.DeleteMessage(request);
        }
        
        public bool DeleteMessage(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, string MsgId) {
            WindowsServiceAppTest.Sales24.DeleteMessageRequest inValue = new WindowsServiceAppTest.Sales24.DeleteMessageRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.CustomInfo = CustomInfo;
            inValue.MsgId = MsgId;
            WindowsServiceAppTest.Sales24.DeleteMessageResponse retVal = ((WindowsServiceAppTest.Sales24.MessageServiceSoap)(this)).DeleteMessage(inValue);
            return retVal.DeleteMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.DeleteMessageResponse> WindowsServiceAppTest.Sales24.MessageServiceSoap.DeleteMessageAsync(WindowsServiceAppTest.Sales24.DeleteMessageRequest request) {
            return base.Channel.DeleteMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.DeleteMessageResponse> DeleteMessageAsync(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, string MsgId) {
            WindowsServiceAppTest.Sales24.DeleteMessageRequest inValue = new WindowsServiceAppTest.Sales24.DeleteMessageRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.CustomInfo = CustomInfo;
            inValue.MsgId = MsgId;
            return ((WindowsServiceAppTest.Sales24.MessageServiceSoap)(this)).DeleteMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsServiceAppTest.Sales24.PostMessageResponse WindowsServiceAppTest.Sales24.MessageServiceSoap.PostMessage(WindowsServiceAppTest.Sales24.PostMessageRequest request) {
            return base.Channel.PostMessage(request);
        }
        
        public bool PostMessage(WindowsServiceAppTest.Sales24.AuthenticationInfo AuthenticationInfo, WindowsServiceAppTest.Sales24.CustomInfo CustomInfo, ref WindowsServiceAppTest.Sales24.MessageServiceMessage MessageServiceMessage) {
            WindowsServiceAppTest.Sales24.PostMessageRequest inValue = new WindowsServiceAppTest.Sales24.PostMessageRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.CustomInfo = CustomInfo;
            inValue.MessageServiceMessage = MessageServiceMessage;
            WindowsServiceAppTest.Sales24.PostMessageResponse retVal = ((WindowsServiceAppTest.Sales24.MessageServiceSoap)(this)).PostMessage(inValue);
            MessageServiceMessage = retVal.MessageServiceMessage;
            return retVal.PostMessageResult;
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAppTest.Sales24.PostMessageResponse> PostMessageAsync(WindowsServiceAppTest.Sales24.PostMessageRequest request) {
            return base.Channel.PostMessageAsync(request);
        }
    }
}
