//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsServiceAppTest.MaterieelWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/Kraan.WebservicesTemplate")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppVersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceOSVersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GebruikersNaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPhraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WachtwoordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode {
            get {
                return this.AppCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AppCodeField, value) != true)) {
                    this.AppCodeField = value;
                    this.RaisePropertyChanged("AppCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppVersie {
            get {
                return this.AppVersieField;
            }
            set {
                if ((object.ReferenceEquals(this.AppVersieField, value) != true)) {
                    this.AppVersieField = value;
                    this.RaisePropertyChanged("AppVersie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceOS {
            get {
                return this.DeviceOSField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceOSField, value) != true)) {
                    this.DeviceOSField = value;
                    this.RaisePropertyChanged("DeviceOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceOSVersie {
            get {
                return this.DeviceOSVersieField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceOSVersieField, value) != true)) {
                    this.DeviceOSVersieField = value;
                    this.RaisePropertyChanged("DeviceOSVersie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GebruikersNaam {
            get {
                return this.GebruikersNaamField;
            }
            set {
                if ((object.ReferenceEquals(this.GebruikersNaamField, value) != true)) {
                    this.GebruikersNaamField = value;
                    this.RaisePropertyChanged("GebruikersNaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPhrase {
            get {
                return this.UserPhraseField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPhraseField, value) != true)) {
                    this.UserPhraseField = value;
                    this.RaisePropertyChanged("UserPhrase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wachtwoord {
            get {
                return this.WachtwoordField;
            }
            set {
                if ((object.ReferenceEquals(this.WachtwoordField, value) != true)) {
                    this.WachtwoordField = value;
                    this.RaisePropertyChanged("Wachtwoord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRegistratie", Namespace="http://schemas.datacontract.org/2004/07/Kraan.WebservicesTemplate")]
    [System.SerializableAttribute()]
    public partial class LoginRegistratie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MeldingenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WebserverVersienummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Meldingen {
            get {
                return this.MeldingenField;
            }
            set {
                if ((object.ReferenceEquals(this.MeldingenField, value) != true)) {
                    this.MeldingenField = value;
                    this.RaisePropertyChanged("Meldingen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes {
            get {
                return this.SuccesField;
            }
            set {
                if ((this.SuccesField.Equals(value) != true)) {
                    this.SuccesField = value;
                    this.RaisePropertyChanged("Succes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WebserverVersienummer {
            get {
                return this.WebserverVersienummerField;
            }
            set {
                if ((this.WebserverVersienummerField.Equals(value) != true)) {
                    this.WebserverVersienummerField = value;
                    this.RaisePropertyChanged("WebserverVersienummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestAuth", Namespace="http://schemas.datacontract.org/2004/07/Kraan.WebservicesTemplate")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsServiceAppTest.MaterieelWebservice.RequestRFIDArtikel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsServiceAppTest.MaterieelWebservice.RequestSaveBon))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsServiceAppTest.MaterieelWebservice.RequestSearch))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsServiceAppTest.MaterieelWebservice.RequestStamModelData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsServiceAppTest.MaterieelWebservice.RequestArtikelVoorraad))]
    public partial class RequestAuth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppVersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceOSVersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GebruikersNaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode {
            get {
                return this.AppCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AppCodeField, value) != true)) {
                    this.AppCodeField = value;
                    this.RaisePropertyChanged("AppCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppVersie {
            get {
                return this.AppVersieField;
            }
            set {
                if ((object.ReferenceEquals(this.AppVersieField, value) != true)) {
                    this.AppVersieField = value;
                    this.RaisePropertyChanged("AppVersie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceOS {
            get {
                return this.DeviceOSField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceOSField, value) != true)) {
                    this.DeviceOSField = value;
                    this.RaisePropertyChanged("DeviceOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceOSVersie {
            get {
                return this.DeviceOSVersieField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceOSVersieField, value) != true)) {
                    this.DeviceOSVersieField = value;
                    this.RaisePropertyChanged("DeviceOSVersie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GebruikersNaam {
            get {
                return this.GebruikersNaamField;
            }
            set {
                if ((object.ReferenceEquals(this.GebruikersNaamField, value) != true)) {
                    this.GebruikersNaamField = value;
                    this.RaisePropertyChanged("GebruikersNaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestRFIDArtikel", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class RequestRFIDArtikel : WindowsServiceAppTest.MaterieelWebservice.RequestAuth {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ServerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFID {
            get {
                return this.RFIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RFIDField, value) != true)) {
                    this.RFIDField = value;
                    this.RaisePropertyChanged("RFID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ServerId {
            get {
                return this.ServerIdField;
            }
            set {
                if ((this.ServerIdField.Equals(value) != true)) {
                    this.ServerIdField = value;
                    this.RaisePropertyChanged("ServerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestSaveBon", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class RequestSaveBon : WindowsServiceAppTest.MaterieelWebservice.RequestAuth {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.MaterieelBon BonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.MaterieelBon Bon {
            get {
                return this.BonField;
            }
            set {
                if ((object.ReferenceEquals(this.BonField, value) != true)) {
                    this.BonField = value;
                    this.RaisePropertyChanged("Bon");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class RequestSearch {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class RequestStamModelData {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class RequestArtikelVoorraad {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaterieelBon", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class MaterieelBon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AppGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BonDatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocatieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaarLocatieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaarSoortLocatieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaarWerkbonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.ArtikelMaterieel[] RegelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoortLocatieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.BonType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WerkbonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid WerkbonIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AppGuid {
            get {
                return this.AppGuidField;
            }
            set {
                if ((this.AppGuidField.Equals(value) != true)) {
                    this.AppGuidField = value;
                    this.RaisePropertyChanged("AppGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BonDatum {
            get {
                return this.BonDatumField;
            }
            set {
                if ((this.BonDatumField.Equals(value) != true)) {
                    this.BonDatumField = value;
                    this.RaisePropertyChanged("BonDatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BonID {
            get {
                return this.BonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BonIDField, value) != true)) {
                    this.BonIDField = value;
                    this.RaisePropertyChanged("BonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locatie {
            get {
                return this.LocatieField;
            }
            set {
                if ((object.ReferenceEquals(this.LocatieField, value) != true)) {
                    this.LocatieField = value;
                    this.RaisePropertyChanged("Locatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NaarLocatie {
            get {
                return this.NaarLocatieField;
            }
            set {
                if ((object.ReferenceEquals(this.NaarLocatieField, value) != true)) {
                    this.NaarLocatieField = value;
                    this.RaisePropertyChanged("NaarLocatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NaarSoortLocatie {
            get {
                return this.NaarSoortLocatieField;
            }
            set {
                if ((object.ReferenceEquals(this.NaarSoortLocatieField, value) != true)) {
                    this.NaarSoortLocatieField = value;
                    this.RaisePropertyChanged("NaarSoortLocatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NaarWerkbon {
            get {
                return this.NaarWerkbonField;
            }
            set {
                if ((object.ReferenceEquals(this.NaarWerkbonField, value) != true)) {
                    this.NaarWerkbonField = value;
                    this.RaisePropertyChanged("NaarWerkbon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.ArtikelMaterieel[] Regels {
            get {
                return this.RegelsField;
            }
            set {
                if ((object.ReferenceEquals(this.RegelsField, value) != true)) {
                    this.RegelsField = value;
                    this.RaisePropertyChanged("Regels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoortLocatie {
            get {
                return this.SoortLocatieField;
            }
            set {
                if ((object.ReferenceEquals(this.SoortLocatieField, value) != true)) {
                    this.SoortLocatieField = value;
                    this.RaisePropertyChanged("SoortLocatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.BonType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Werkbon {
            get {
                return this.WerkbonField;
            }
            set {
                if ((object.ReferenceEquals(this.WerkbonField, value) != true)) {
                    this.WerkbonField = value;
                    this.RaisePropertyChanged("Werkbon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WerkbonId {
            get {
                return this.WerkbonIdField;
            }
            set {
                if ((this.WerkbonIdField.Equals(value) != true)) {
                    this.WerkbonIdField = value;
                    this.RaisePropertyChanged("WerkbonId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtikelMaterieel", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsServiceAppTest.MaterieelWebservice.ResponseArtikelMaterieel))]
    public partial class ArtikelMaterieel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AantalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AfbeeldingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.Document[] BijlagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GroepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroepCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InHuurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KeurenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.KeuringsInformatie[] KeuringsInformatieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.ArtikelLocatieInfo[] LocatiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MutatieCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServiceOpdrachtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoortLocatieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.TechnischeSpecsArtikel[] TechnischeSpecificatiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.Type TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UniekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VanLocatieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WerkbonNummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Aantal {
            get {
                return this.AantalField;
            }
            set {
                if ((this.AantalField.Equals(value) != true)) {
                    this.AantalField = value;
                    this.RaisePropertyChanged("Aantal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Afbeelding {
            get {
                return this.AfbeeldingField;
            }
            set {
                if ((object.ReferenceEquals(this.AfbeeldingField, value) != true)) {
                    this.AfbeeldingField = value;
                    this.RaisePropertyChanged("Afbeelding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.Document[] Bijlages {
            get {
                return this.BijlagesField;
            }
            set {
                if ((object.ReferenceEquals(this.BijlagesField, value) != true)) {
                    this.BijlagesField = value;
                    this.RaisePropertyChanged("Bijlages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Groep {
            get {
                return this.GroepField;
            }
            set {
                if ((this.GroepField.Equals(value) != true)) {
                    this.GroepField = value;
                    this.RaisePropertyChanged("Groep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroepCode {
            get {
                return this.GroepCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GroepCodeField, value) != true)) {
                    this.GroepCodeField = value;
                    this.RaisePropertyChanged("GroepCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InHuur {
            get {
                return this.InHuurField;
            }
            set {
                if ((this.InHuurField.Equals(value) != true)) {
                    this.InHuurField = value;
                    this.RaisePropertyChanged("InHuur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Keuren {
            get {
                return this.KeurenField;
            }
            set {
                if ((this.KeurenField.Equals(value) != true)) {
                    this.KeurenField = value;
                    this.RaisePropertyChanged("Keuren");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.KeuringsInformatie[] KeuringsInformatie {
            get {
                return this.KeuringsInformatieField;
            }
            set {
                if ((object.ReferenceEquals(this.KeuringsInformatieField, value) != true)) {
                    this.KeuringsInformatieField = value;
                    this.RaisePropertyChanged("KeuringsInformatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.ArtikelLocatieInfo[] Locaties {
            get {
                return this.LocatiesField;
            }
            set {
                if ((object.ReferenceEquals(this.LocatiesField, value) != true)) {
                    this.LocatiesField = value;
                    this.RaisePropertyChanged("Locaties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MutatieCode {
            get {
                return this.MutatieCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MutatieCodeField, value) != true)) {
                    this.MutatieCodeField = value;
                    this.RaisePropertyChanged("MutatieCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFID {
            get {
                return this.RFIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RFIDField, value) != true)) {
                    this.RFIDField = value;
                    this.RaisePropertyChanged("RFID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServiceOpdracht {
            get {
                return this.ServiceOpdrachtField;
            }
            set {
                if ((this.ServiceOpdrachtField.Equals(value) != true)) {
                    this.ServiceOpdrachtField = value;
                    this.RaisePropertyChanged("ServiceOpdracht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoortLocatie {
            get {
                return this.SoortLocatieField;
            }
            set {
                if ((object.ReferenceEquals(this.SoortLocatieField, value) != true)) {
                    this.SoortLocatieField = value;
                    this.RaisePropertyChanged("SoortLocatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.TechnischeSpecsArtikel[] TechnischeSpecificaties {
            get {
                return this.TechnischeSpecificatiesField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnischeSpecificatiesField, value) != true)) {
                    this.TechnischeSpecificatiesField = value;
                    this.RaisePropertyChanged("TechnischeSpecificaties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.Type Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Uniek {
            get {
                return this.UniekField;
            }
            set {
                if ((this.UniekField.Equals(value) != true)) {
                    this.UniekField = value;
                    this.RaisePropertyChanged("Uniek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VanLocatie {
            get {
                return this.VanLocatieField;
            }
            set {
                if ((object.ReferenceEquals(this.VanLocatieField, value) != true)) {
                    this.VanLocatieField = value;
                    this.RaisePropertyChanged("VanLocatie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WerkbonNummer {
            get {
                return this.WerkbonNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.WerkbonNummerField, value) != true)) {
                    this.WerkbonNummerField = value;
                    this.RaisePropertyChanged("WerkbonNummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class BonType {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class ResponseArtikelMaterieel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AanmaakDatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AppCreationGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BestandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocutypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AanmaakDatum {
            get {
                return this.AanmaakDatumField;
            }
            set {
                if ((this.AanmaakDatumField.Equals(value) != true)) {
                    this.AanmaakDatumField = value;
                    this.RaisePropertyChanged("AanmaakDatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AppCreationGuid {
            get {
                return this.AppCreationGuidField;
            }
            set {
                if ((this.AppCreationGuidField.Equals(value) != true)) {
                    this.AppCreationGuidField = value;
                    this.RaisePropertyChanged("AppCreationGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bestand {
            get {
                return this.BestandField;
            }
            set {
                if ((object.ReferenceEquals(this.BestandField, value) != true)) {
                    this.BestandField = value;
                    this.RaisePropertyChanged("Bestand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Docutype {
            get {
                return this.DocutypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocutypeField, value) != true)) {
                    this.DocutypeField = value;
                    this.RaisePropertyChanged("Docutype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extensie {
            get {
                return this.ExtensieField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensieField, value) != true)) {
                    this.ExtensieField = value;
                    this.RaisePropertyChanged("Extensie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pad {
            get {
                return this.PadField;
            }
            set {
                if ((object.ReferenceEquals(this.PadField, value) != true)) {
                    this.PadField = value;
                    this.RaisePropertyChanged("Pad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeuringsInformatie", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class KeuringsInformatie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.KeuringDetails[] DetailRegelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InhuurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoortKeuringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UitgevoerdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VolgendeKeuringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.KeuringDetails[] DetailRegels {
            get {
                return this.DetailRegelsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailRegelsField, value) != true)) {
                    this.DetailRegelsField = value;
                    this.RaisePropertyChanged("DetailRegels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Inhuur {
            get {
                return this.InhuurField;
            }
            set {
                if ((this.InhuurField.Equals(value) != true)) {
                    this.InhuurField = value;
                    this.RaisePropertyChanged("Inhuur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoortKeuring {
            get {
                return this.SoortKeuringField;
            }
            set {
                if ((object.ReferenceEquals(this.SoortKeuringField, value) != true)) {
                    this.SoortKeuringField = value;
                    this.RaisePropertyChanged("SoortKeuring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Uitgevoerd {
            get {
                return this.UitgevoerdField;
            }
            set {
                if ((this.UitgevoerdField.Equals(value) != true)) {
                    this.UitgevoerdField = value;
                    this.RaisePropertyChanged("Uitgevoerd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VolgendeKeuring {
            get {
                return this.VolgendeKeuringField;
            }
            set {
                if ((this.VolgendeKeuringField.Equals(value) != true)) {
                    this.VolgendeKeuringField = value;
                    this.RaisePropertyChanged("VolgendeKeuring");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtikelLocatieInfo", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class ArtikelLocatieInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AantalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.ArtikelLocatieInfo.ArtikelLocatieAdres AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.ArtikelLocatieInfo.ArtikelRelatie[] RelatiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Aantal {
            get {
                return this.AantalField;
            }
            set {
                if ((this.AantalField.Equals(value) != true)) {
                    this.AantalField = value;
                    this.RaisePropertyChanged("Aantal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.ArtikelLocatieInfo.ArtikelLocatieAdres Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.ArtikelLocatieInfo.ArtikelRelatie[] Relaties {
            get {
                return this.RelatiesField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatiesField, value) != true)) {
                    this.RelatiesField = value;
                    this.RaisePropertyChanged("Relaties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ArtikelLocatieInfo.ArtikelLocatieAdres", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
        [System.SerializableAttribute()]
        public partial class ArtikelLocatieAdres : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NummerField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PlaatsField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PostcodeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string StraatField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ToevoegingField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Nummer {
                get {
                    return this.NummerField;
                }
                set {
                    if ((object.ReferenceEquals(this.NummerField, value) != true)) {
                        this.NummerField = value;
                        this.RaisePropertyChanged("Nummer");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Plaats {
                get {
                    return this.PlaatsField;
                }
                set {
                    if ((object.ReferenceEquals(this.PlaatsField, value) != true)) {
                        this.PlaatsField = value;
                        this.RaisePropertyChanged("Plaats");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Postcode {
                get {
                    return this.PostcodeField;
                }
                set {
                    if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                        this.PostcodeField = value;
                        this.RaisePropertyChanged("Postcode");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Straat {
                get {
                    return this.StraatField;
                }
                set {
                    if ((object.ReferenceEquals(this.StraatField, value) != true)) {
                        this.StraatField = value;
                        this.RaisePropertyChanged("Straat");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Toevoeging {
                get {
                    return this.ToevoegingField;
                }
                set {
                    if ((object.ReferenceEquals(this.ToevoegingField, value) != true)) {
                        this.ToevoegingField = value;
                        this.RaisePropertyChanged("Toevoeging");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ArtikelLocatieInfo.ArtikelRelatie", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
        [System.SerializableAttribute()]
        public partial class ArtikelRelatie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string EmailField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NaamField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TelefoonnummerField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TelefoonnummerZakelijkField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Email {
                get {
                    return this.EmailField;
                }
                set {
                    if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                        this.EmailField = value;
                        this.RaisePropertyChanged("Email");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Naam {
                get {
                    return this.NaamField;
                }
                set {
                    if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                        this.NaamField = value;
                        this.RaisePropertyChanged("Naam");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Telefoonnummer {
                get {
                    return this.TelefoonnummerField;
                }
                set {
                    if ((object.ReferenceEquals(this.TelefoonnummerField, value) != true)) {
                        this.TelefoonnummerField = value;
                        this.RaisePropertyChanged("Telefoonnummer");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string TelefoonnummerZakelijk {
                get {
                    return this.TelefoonnummerZakelijkField;
                }
                set {
                    if ((object.ReferenceEquals(this.TelefoonnummerZakelijkField, value) != true)) {
                        this.TelefoonnummerZakelijkField = value;
                        this.RaisePropertyChanged("TelefoonnummerZakelijk");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TechnischeSpecsArtikel", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class TechnischeSpecsArtikel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.Image AfbeeldingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.Image Afbeelding {
            get {
                return this.AfbeeldingField;
            }
            set {
                if ((object.ReferenceEquals(this.AfbeeldingField, value) != true)) {
                    this.AfbeeldingField = value;
                    this.RaisePropertyChanged("Afbeelding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class Type {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeuringDetails", Namespace="http://schemas.datacontract.org/2004/07/Kraan2.Webservices.Model")]
    [System.SerializableAttribute()]
    public partial class KeuringDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EenheidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GoedgekeurdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsServiceAppTest.MaterieelWebservice.KeuringsTestStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WaardeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eenheid {
            get {
                return this.EenheidField;
            }
            set {
                if ((object.ReferenceEquals(this.EenheidField, value) != true)) {
                    this.EenheidField = value;
                    this.RaisePropertyChanged("Eenheid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Goedgekeurd {
            get {
                return this.GoedgekeurdField;
            }
            set {
                if ((this.GoedgekeurdField.Equals(value) != true)) {
                    this.GoedgekeurdField = value;
                    this.RaisePropertyChanged("Goedgekeurd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsServiceAppTest.MaterieelWebservice.KeuringsTestStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Waarde {
            get {
                return this.WaardeField;
            }
            set {
                if ((object.ReferenceEquals(this.WaardeField, value) != true)) {
                    this.WaardeField = value;
                    this.RaisePropertyChanged("Waarde");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeuringsTestStatus", Namespace="http://schemas.datacontract.org/2004/07/Kraan.Model.Probis.Voorraad")]
    public enum KeuringsTestStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Foutief = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Goed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Overgeslagen = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Informatie = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reparatie = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Onbekend = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    public class Image {
    }
}
